name: Build Release

permissions:
  # Allows workflow to create a new tag and release in this repository
  contents: write
  # Allows workflow to publish Docker images
  packages: write

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    
     
env:
  GO_VERSION: 1.19
  AWS_REGION: us-east-1

jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: "Create Version Number"
        run: |
          echo "VERSION=`date '+%Y%m%d'`-`echo ${{github.sha}} | head -c 7`" >> $GITHUB_ENV
          echo "${{ env.VERSION }}"
     
      - name: Get Branch Name
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Create Image Tag
        run: |
          if [[ "${{ env.BRANCH_NAME }}" != "master" && $GITHUB_EVENT_NAME == "workflow_dispatch" ]]; then
              echo "IMAGE_TAG=v${{ env.VERSION }}-hotfix" >> $GITHUB_ENV
          else
              echo "IMAGE_TAG=v${{ env.VERSION }}" >> $GITHUB_ENV
          fi    

      - name: "GET Image Tag"
        run: |
          echo "${{ env.IMAGE_TAG }}" 

      - name: "Release - Push Docker Image to GHCR"
        env:
          GHCR_REGISTRY: docker.pkg.github.com/neelimashrm/ghcr-phanes
          GHCR_REPOSITORY: ghcr-phanes
        run: |
          docker build -t $GHCR_REGISTRY/$GHCR_REPOSITORY:${{ env.IMAGE_TAG }} .
          docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          echo "Pushing to GHCR..."
          docker push $GHCR_REGISTRY/$GHCR_REPOSITORY:${{ env.IMAGE_TAG }}
          echo "Docker image pushed to GHCR"
          docker images    

      - name: "Release - Create Release"
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: ${{ github.ref }}
          tag_name: ${{ env.IMAGE_TAG }}
          name: Release ${{ env.IMAGE_TAG }}
          draft: false
          prerelease: false    

      - name: "Release - Delete Release"
        id: delete_release
        uses: dev-drprasad/delete-tag-and-release@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.IMAGE_TAG }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true

      - name: "Package - Delete Package"  
        id: delete_package
        uses: actions/delete-package-versions@v4
        with:
           package-version-ids: ${{ env.IMAGE_TAG }}
           package-name: 'ghcr-phanes'
           token: ${{ secrets.GITHUB_TOKEN }}
