name: Build Release

permissions:
  # Allows workflow to create a new tag and release in this repository
  contents: write
  # Allows workflow to publish Docker images
  packages: write

on:
  workflow_dispatch:
  push:
    branches: ["master"]

env:
  GO_VERSION: 1.19
  AWS_REGION: us-east-1

jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: "Create Version Number"
        run: |
          echo "VERSION=`date '+%Y%m%d'`-`echo ${{github.sha}} | head -c 7`" >> $GITHUB_ENV
          echo "${{ env.VERSION }}"

      - name: "Create Image Tag"
        env:
          IMAGE_TAG: v${{ env.VERSION }}-hotfix
        run: |
          echo "${{ env.IMAGE_TAG }}"    
