name: Build Release

permissions:
  # Allows workflow to create a new tag and release in this repository
  contents: write
  # Allows workflow to publish Docker images
  packages: write

on:
  workflow_dispatch:
    
     
env:
  GO_VERSION: 1.19
  AWS_REGION: us-east-1

jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: "Create Version Number"
        run: |
          echo "VERSION=`date '+%Y%m%d'`-`echo ${{github.sha}} | head -c 7`" >> $GITHUB_ENV
          echo "${{ env.VERSION }}"
     
      - name: Get Branch Name
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          fi
          echo "${{ github.event.action }}"
          echo "${{ github.event_name }}"

      - name: 'Release - Check Requested'
        if: (github.event_name == 'workflow_dispatch')
        run: |
          echo "release_requested=true" >> $GITHUB_ENV  
          echo "${{ env.release_requested }}"

      - name: Create Image Tag
        run: |
          if [[ "${{ env.BRANCH_NAME }}" != "master" && $GITHUB_EVENT_NAME == "workflow_dispatch" ]]; then
              echo "IMAGE_TAG=v${{ env.VERSION }}-hotfix" >> $GITHUB_ENV
          else
              echo "IMAGE_TAG=v${{ env.VERSION }}" >> $GITHUB_ENV
          fi  
          echo "${{ env.release_requested }}"

      - name: "GET Image Tag"
        run: |
          echo "${{ env.IMAGE_TAG }}" 

      - name: "Release - Push Docker Image to GHCR"
        env:
          GHCR_REGISTRY: docker.pkg.github.com/neelimashrm/ghcr-phanes
          GHCR_REPOSITORY: ghcr-phanes
        run: |
          docker build -t $GHCR_REGISTRY/$GHCR_REPOSITORY:${{ env.IMAGE_TAG }} .
          docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          echo "Pushing to GHCR..."
          docker push $GHCR_REGISTRY/$GHCR_REPOSITORY:${{ env.IMAGE_TAG }}
          echo "Docker image pushed to GHCR"
          docker images 

      - name: "Release - Create Release"
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: ${{ github.ref }}
          tag_name: ${{ env.IMAGE_TAG }}
          name: Release ${{ env.IMAGE_TAG }}
          draft: false
          prerelease: false
