name: Build Release

permissions:
  # Allows workflow to create a new tag and release in this repository
  contents: write
  # Allows workflow to publish Docker images
  packages: write

on:
  workflow_dispatch:
  push:
    branches: "hotfix-test"
    
     
env:
  GO_VERSION: 1.19
  AWS_REGION: us-east-1

jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: "Create Version Number"
        run: |
          echo "${{ github.ref }}"
          echo "VERSION=`date '+%Y%m%d'`-`echo ${{github.sha}} | head -c 7`" >> $GITHUB_ENV
          echo "${{ env.VERSION }}"
     
      - name: Get Branch Name
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Create Image Tag
        run: |
          if [[ "${{ env.BRANCH_NAME }}" != "master" && $GITHUB_EVENT_NAME == "workflow_dispatch" ]]; then
              echo "IMAGE_TAG=v${{ env.VERSION }}-hotfix" >> $GITHUB_ENV
          else
              echo "IMAGE_TAG=v${{ env.VERSION }}" >> $GITHUB_ENV
          fi    

      - name: "GET Image Tag"
        run: |
          echo "${{ env.IMAGE_TAG }}" 

      - name: "Release - Create Release"
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: ${{ github.ref }}
          tag_name: ${{ env.IMAGE_TAG }}
          name: Release ${{ env.IMAGE_TAG }}
          draft: false
          prerelease: false     
