name: Build Release

permissions:
  # Allows workflow to create a new tag and release in this repository
  contents: write
  # Allows workflow to publish Docker images
  packages: write

on:
  workflow_dispatch:
   inputs:
      branch:
        description: 'Define branch name'     
        required: true
        default: 'master'
  push:
    branches: ["master"]
     
env:
  GO_VERSION: 1.19
  AWS_REGION: us-east-1

jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: "Create Version Number"
        run: |
          echo "VERSION=`date '+%Y%m%d'`-`echo ${{github.sha}} | head -c 7`" >> $GITHUB_ENV
          echo "${{ env.VERSION }}"
     
      # print branch name
      - name: Get branch name
        run: | 
          echo "Branch Name: ${{ github.event.inputs.branch }}"

      - name: Set env IMAGE TAG
        run: |
          echo ${{ github.event_name }}
          if [[ "${{ env.BRANCH_NAME }}" != 'master' && $GITHUB_EVENT_NAME == 'workflow_dispatch' ]]; then
              echo "IMAGE_TAG= v${{ env.VERSION }}-hotfix" >> $GITHUB_ENV || exit 1
          else
              echo "IMAGE_TAG= v${{ env.VERSION }}" >> $GITHUB_ENV || exit 1
          fi    

      - name: "GET Image Tag"
        run: |
          echo "${{ env.IMAGE_TAG }}"    
