name: "delete-prerelease-packages-ghcr"
'on':
  workflow_dispatch:
 # schedule:
 #   - cron: "*/5 * * * *"

jobs:
  delete-prerelease-packages:
    name: Delete packages pushed to ghcr.io
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name : Delete Prerelease version
      uses: actions/delete-package-versions@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        package-name: 'ghcr-phanes/ghcr-phanes'
        package-type: 'container'
        min-versions-to-keep: 1
        delete-only-pre-release-versions: "true"
