name: Delete Release

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    
jobs:
  delete-release:
    name: Delete image from ghcr.io
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: "Delete release and tag"
        id : delete-tag-release
        uses: dev-drprasad/delete-tag-and-release@v1.0.1 # PRERELEASE is v1.0 and can also be used to test and give us feedback
        with:
          tag_name: v20230825-abbd324-hotfix #(required) tag name to delete 
          github_token: ${{ secrets.GITHUB_TOKEN }} # (required) a GitHub token with write access to the repo that needs to be modified
          delete_release: true #(optional) default: true 
          #repo: <owner>/<repoName> #(optional) target repository. default: repo running this action
