name: Delete Release

on:
  workflow_dispatch:
    
jobs:
  delete-release:
    name: Delete image from ghcr.io
    environment: dev
    runs-on: ubuntu-latest
    steps:
   # - name : Delete Prerelease version
   #   uses: actions/delete-package-versions@v4
   #   env:
   #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   #   with: 
   #     package-name: 'ghcr-phanes/ghcr-phanes'
   #     package-type: 'container'
   #     min-versions-to-keep: 1
   #     delete-only-pre-release-versions: "true"

    # - name : Delete new 
    #   uses: liudonghua123/delete-release-action@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
       #  release_name: 'Release v20230827-40b5227'

    - name: "Delete release and tag"
      id : delete-tag-release
      uses: dev-drprasad/delete-tag-and-release@v1.0.1 # PRERELEASE is v1.0 and can also be used to test and give us feedback
      with:
          tag_name: v20230828-eeee5e5 #(required) tag name to delete 
          github_token: ${{ secrets.GITHUB_TOKEN }} # (required) a GitHub token with write access to the repo that needs to be modified
          delete_release: true #(optional) default: true 
          #repo: <owner>/<repoName> #(optional) target repository. default: repo running this action
