name: Delete old container images

'on':
  workflow_dispatch:
  #schedule:
  #  - cron: "*/5 * * * *"  # every five mins
  
jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete containers older images 
        uses: snok/container-retention-policy@v2.1.2
        with:
          image-names: v*
          cut-off: Two hours ago UTC
          timestamp-to-use: created_at
          account-type: personal
          token: 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
          dry-run: true
