name: Delete GHCR Package Release Tag

on:
  workflow_dispatch:

jobs:
  delete_tag_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Delete GHCR Package
      env:
        CR_PAT: ${{ secrets.GITHUB_TOKEN }}  # GitHub Personal Access Token with package:read and package:delete scope
        
      run: |
        # Delete package from GHCR
        PACKAGE_ID=$(curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $CR_PAT" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/users/NeelimaShrm/packages/container/ghcr-phanes%2Fghcr-phanes/versions  | jq '.[].id')

        echo $PACKAGE_ID
    
    -  name: Delete
       uses: actions/delete-package-versions@v4
       with:
         owner: 'NeelimaShrm'
         package-name: 'ghcr-phanes/ghcr-phanes'
         package-type: 'container'
         #num-old-versions-to-delete: 1
         package-version-ids: $PACKAGE_ID
         #min-versions-to-keep: 1
         #delete-only-pre-release-versions: "true"
         token: ${{ secrets.GITHUB_TOKEN }} 
