name: Delete GHCR Package Release Tag

on:
  workflow_dispatch:

jobs:
  delete_tag_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Fetch GHCR Package Version ID
      env:
        CR_PAT: ${{ secrets.GITHUB_TOKEN }}  # GitHub Personal Access Token with package:read and package:delete scope
        
      run: |
        # Delete package from GHCR
        PACKAGE_ID=$(curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $CR_PAT" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/users/NeelimaShrm/packages/container/ghcr-phanes%2Fghcr-phanes/versions  | jq '.[].id')

        echo $PACKAGE_ID

    - name: Delete GHCR Package By Version ID
      env:
        CR_PAT: ${{ secrets.GITHUB_TOKEN }}  # GitHub Personal Access Token with package:read and package:delete scope
        
      run: |
        # Delete package from GHCR
        curl -X POST \
        -H "Accept: application/vnd.github.package-deletes-preview+json" \
        -H "Authorization: bearer TOKEN" \
        -d '{"query":"mutation { deletePackageVersion(input:{packageVersionId:\$PACKAGE_ID}) { success }}"}' \
       
         
