name: Delete old container images

'on':
  workflow_dispatch:
  #schedule:
  #  - cron: "*/5 * * * *"  # every five mins
  
jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete containers older images 
        uses: snok/container-retention-policy@v2.1.2
        with:
          image_names: v*
          cut_off: Two hours ago UTC
          timestamp_to_use: created_at
          account_type: personal
          token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
