name: Delete GHCR Package Release Tag

on:
  workflow_dispatch:

jobs:
  delete_tag_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Fetch GHCR Package Version ID
      env:
        CR_PAT: ${{ secrets.GITHUB_TOKEN }}  # GitHub Personal Access Token with package:read and package:delete scope
        
      run: |
        # Delete package from GHCR
        PACKAGE_ID=$(curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $CR_PAT" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/users/NeelimaShrm/packages/container/ghcr-phanes%2Fghcr-phanes/versions  | jq '.[].id')

        echo PKG_ID = $PACKAGE_ID >> GITHUB_ENV

    - name: Delete GHCR Package By Version ID
      env:
        CR_PAT: ${{ secrets.GITHUB_TOKEN }}  # GitHub Personal Access Token with package:read and package:delete scope
        PACKAGE_TYPE: container
        PACKAGE_NAME: ghcr-phanes%2Fghcr-phanes
      run: |
        # Delete package from GHCR
        echo ${{env.PKG_ID}}
        curl -L \
        -X DELETE \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $CR_PAT" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/user/packages/${{env.PACKAGE_TYPE}}/${{env.PACKAGE_NAME}}/versions/${{env.PKG_ID}}
