name: Cleanup PR Images

on:
  workflow_dispatch:

jobs:
  delete-release:
    name: Delete image from ghcr.io
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          # NOTE: at now only orgs is supported
          owner: NeelimaShrm
          name: SpringBoot
          # NOTE: using Personal Access Token
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v20230827-fec28f4-hotfix
